[versions]

android-gradle-plugin = "8.0.0"
androidx-core-ktx = "1.10.1"
androidx-core-core-splashscreen = "1.0.1"
org-jetbrains-kotlin-android = "1.8.0"
com-google-devtools-ksp = "1.8.10-1.0.9"
com-google-dagger-hilt-android = "2.44"
com-google-gms-google-services = "4.3.15"

#kotlin = "1.5.31"
#coreSplashscreen = "1.0.1"
#appcompat = "1.6.1"
#material = "1.9.0"
#constraintlayout = "2.1.4"
#testJunit = "4.13.2"
#androidTestjunit = "1.1.5"
#androidTestEspressoCore = "3.5.1"

[libraries]
androidx-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "androidx-core-ktx" }
androidx-splashscreen = { group = "androidx.core:core-splashscreen", name = "core-ktx", version.ref = "androidx-core-core-splashscreen" }

[plugins]
android-application = { id = "com.android.application", version.ref = "android-gradle-plugin" }
android-library = { id = "com.android.library", version.ref = "android-gradle-plugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "org-jetbrains-kotlin-android" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "org-jetbrains-kotlin-android" }
dagger-hilt = { id = "com.google.dagger.hilt.android", version.ref = "com-google-dagger-hilt-android" }
devtools-ksp = { id = "com.google.devtools.ksp", version.ref = "com-google-devtools-ksp" }
gms-google-services = { id = "com.google.gms.google-services", version.ref = "com-google-gms-google-services" }

[bundles]
