[versions]

ktx = "1.10.1"
androidGradlePlugin = "8.0.0"

#kotlin = "1.5.31"
#coreSplashscreen = "1.0.1"
#appcompat = "1.6.1"
#material = "1.9.0"
#constraintlayout = "2.1.4"
#testJunit = "4.13.2"
#androidTestjunit = "1.1.5"
#androidTestEspressoCore = "3.5.1"

[libraries]
androidx-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "ktx" }

[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }

[bundles]
